### ISSUE TITLE
Unable to get schema template to work

### ISSUE THREAD

**Issue by ericthomas1** [kevinslin/schemas#3]
I'm unable to get a custom schema template to work. Can you see what I'm missing below?

1. Create a new `journal.schema.yml` file in `\Dendron\vault` (my only Dendron workspace):

```
- id: journal
  parent: root
  children:
    - daily
    - weekly
    - yearly
- id: daily
  namespace: true
  template:
    id: journal.template.daily
    type: note
- id: weekly
  namespace: true
- id: yearly
  namespace: true
```

2. Create a new `journal.template.daily.md` file in the same vault:

```
##### Login: 

##### Communications: 

##### Context:

##### Break:

##### Support:

##### Documentation:

##### Research:

##### TIL's:

##### Logout:

##### Duration:
```

![image](https://user-images.githubusercontent.com/42788729/117185688-f3ab8e80-ad8e-11eb-94b8-e4bdd14056e0.png)

3. `Reload index`/close re-open VS Code
- `Dendron is active` shown
- VS Code is properly opened to Workspace

4. Create a new daily journal file (`CTRL+SHIFT+i`)

**Issue:**
- The resulting `daily.journal.2021.05.05.md` file is a bare note, no template applied: 

![image](https://user-images.githubusercontent.com/42788729/117185968-408f6500-ad8f-11eb-960b-8942aad07e74.png)
